language: python

services:
  - postgresql

addons:
  postgresql: "9.6"

python:
  - "3.5"
  - "3.6"
  - "3.7"

sudo: false

env:
  - TOXENV=py35-django-111
  - TOXENV=py35-django-20
  - TOXENV=py36-django-111
  - TOXENV=py36-django-20
  - TOXENV=py36-django-master
  - TOXENV=py37-django-master

matrix:
  allow_failures:
    - env: TOXENV=py36-django-master
    - env: TOXENV=py37-django-master

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install coveralls tox

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - tox -e $TOXENV

after_script:
  - coveralls

notifications:
  email: false
